[meta]
version = "1.0.0-rc.3"

[data.profiles.test]
"Lines/hCMEC_D3" = "Lines/test_hCMEC_D3"

[data.remote]
"https://zenodo.org/records/12687137/files/GSE138309_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE138309_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12687137/files/GSE139133_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE139133_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12687137/files/GSE187565_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE187565_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12687137/files/GSE195781_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE195781_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12687137/files/GSE205739_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE205739_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12687137/files/GSE76528_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE76528_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12687137/files/PRJEB48614_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/PRJEB48614_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12687137/files/PRJNA667281_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/PRJNA667281_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12687137/files/PRJNA896725_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/PRJNA896725_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12687137/files/GSE138309_meta.csv" = "Lines/hCMEC_D3/GSE138309_meta.csv"
"https://zenodo.org/records/12687137/files/GSE139133_meta.csv" = "Lines/hCMEC_D3/GSE139133_meta.csv"
"https://zenodo.org/records/12687137/files/GSE187565_meta.csv" = "Lines/hCMEC_D3/GSE187565_meta.csv"
"https://zenodo.org/records/12687137/files/GSE195781_meta.csv" = "Lines/hCMEC_D3/GSE195781_meta.csv"
"https://zenodo.org/records/12687137/files/GSE205739_meta.csv" = "Lines/hCMEC_D3/GSE205739_meta.csv"
"https://zenodo.org/records/12687137/files/GSE76528_meta.csv" = "Lines/hCMEC_D3/GSE76528_meta.csv"
"https://zenodo.org/records/12687137/files/PRJEB48614_meta.csv" = "Lines/hCMEC_D3/PRJEB48614_meta.csv"
"https://zenodo.org/records/12687137/files/PRJNA667281_meta.csv" = "Lines/hCMEC_D3/PRJNA667281_meta.csv"
"https://zenodo.org/records/12687137/files/PRJNA896725_meta.csv" = "Lines/hCMEC_D3/PRJNA896725_meta.csv"
