[meta]
version = "1.0.0-rc.1"

[data.profiles.test]
"Lines/hCMEC_D3/GSE138309_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/test_GSE138309_CountMatrix_genes_TPM.tsv"
"Lines/hCMEC_D3/GSE139133_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/test_GSE139133_CountMatrix_genes_TPM.tsv"
"Lines/hCMEC_D3/GSE138309_meta.csv" = "Lines/hCMEC_D3/test_GSE138309_meta.csv"
"Lines/hCMEC_D3/GSE139133_meta.csv" = "Lines/hCMEC_D3/test_GSE139133_meta.csv"

[data.remote]
"https://zenodo.org/records/10960146/files/GSE138309_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE138309_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/10960146/files/GSE139133_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE139133_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/10960146/files/GSE195781_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE195781_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/10960146/files/GSE205739_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE205739_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/10960146/files/GSE76528_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE76528_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/10960146/files/GSE138309_meta.csv" = "Lines/hCMEC_D3/GSE138309_meta.csv"
"https://zenodo.org/records/10960146/files/GSE139133_meta.csv" = "Lines/hCMEC_D3/GSE139133_meta.csv"
"https://zenodo.org/records/10960146/files/GSE195781_meta.csv" = "Lines/hCMEC_D3/GSE195781_meta.csv"
"https://zenodo.org/records/10960146/files/GSE205739_meta.csv" = "Lines/hCMEC_D3/GSE205739_meta.csv"
"https://zenodo.org/records/10960146/files/GSE76528_meta.csv" = "Lines/hCMEC_D3/GSE76528_meta.csv"
