[meta]
version = "1.2.1"

[data.profiles.test]
"Lines/hCMEC_D3" = "Lines/test_hCMEC_D3"

[data.remote]
# MTP-DB
"https://github.com/TCP-Lab/MTP-DB/releases/download/1.25.16/MTPDB_v1.25.16.sqlite.gz" = "MTP-DB/MTPDB.sqlite.gz"

# GEO/ENA datasets recomputes from Zenodo
"https://zenodo.org/records/12729454/files/GSE138309_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE138309_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12729454/files/GSE139133_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE139133_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12729454/files/GSE187565_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE187565_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12729454/files/GSE205739_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE205739_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12729454/files/GSE76528_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/GSE76528_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12729454/files/PRJEB48614_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/PRJEB48614_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12729454/files/PRJNA667281_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/PRJNA667281_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12729454/files/PRJNA896725_CountMatrix_genes_TPM.tsv" = "Lines/hCMEC_D3/PRJNA896725_CountMatrix_genes_TPM.tsv"
"https://zenodo.org/records/12729454/files/GSE138309_meta.csv" = "Lines/hCMEC_D3/GSE138309_meta.csv"
"https://zenodo.org/records/12729454/files/GSE139133_meta.csv" = "Lines/hCMEC_D3/GSE139133_meta.csv"
"https://zenodo.org/records/12729454/files/GSE187565_meta.csv" = "Lines/hCMEC_D3/GSE187565_meta.csv"
"https://zenodo.org/records/12729454/files/GSE205739_meta.csv" = "Lines/hCMEC_D3/GSE205739_meta.csv"
"https://zenodo.org/records/12729454/files/GSE76528_meta.csv" = "Lines/hCMEC_D3/GSE76528_meta.csv"
"https://zenodo.org/records/12729454/files/PRJEB48614_meta.csv" = "Lines/hCMEC_D3/PRJEB48614_meta.csv"
"https://zenodo.org/records/12729454/files/PRJNA667281_meta.csv" = "Lines/hCMEC_D3/PRJNA667281_meta.csv"
"https://zenodo.org/records/12729454/files/PRJNA896725_meta.csv" = "Lines/hCMEC_D3/PRJNA896725_meta.csv"
